version: '3.4'

services:
  app:
    build:
      context: .
      target: development
    image: bbb-stress-test:development
    working_dir: /app/
    user: ${DOCKER_USER:-1000}
    cap_add:
      - SYS_ADMIN
    env_file:
      - .env
    volumes:
      - .:/app
